import type { Metadata } from "next";
import { ILayout } from "@/core/interfaces";
import "../core/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AppLayout({ children }: ILayout) {
  return (
    <html lang="ko">
      <body>
        <header>
          header
          <h1>LOGO</h1>
        </header>
        <nav>nav</nav>
        <aside>aside</aside>
        <main>{children}</main>
        <footer>footer</footer>
      </body>
    </html>
  );
}
