import { IMember } from "./Member";

export const GROUP_SIZE_RANGE: [number, number] = [3, 4];

export const MEMBERS: IMember[] = [
  { id: 1, name: "김성무", chapter: "clev", captain_count: 0, group_no: 0 },
  { id: 2, name: "이규민", chapter: "clev", captain_count: 0, group_no: 0 },
  { id: 3, name: "박민성", chapter: "clev", captain_count: 0, group_no: 0 },
  { id: 4, name: "이민호", chapter: "svc", captain_count: 0, group_no: 0 },
  { id: 6, name: "임송이", chapter: "frt", captain_count: 0, group_no: 0 },
  { id: 8, name: "이시원", chapter: "frt", captain_count: 0, group_no: 0 },
  { id: 10, name: "방승민", chapter: "frt", captain_count: 0, group_no: 0 },
  { id: 11, name: "유지연", chapter: "des", captain_count: 0, group_no: 0 },
  { id: 13, name: "서예슬", chapter: "svc", captain_count: 0, group_no: 0 },
  { id: 15, name: "김원일", chapter: "data", captain_count: 0, group_no: 0 },
  { id: 16, name: "사인영", chapter: "ops", captain_count: 0, group_no: 0 },
  { id: 18, name: "박지유", chapter: "be", captain_count: 0, group_no: 0 },
  { id: 19, name: "최고은", chapter: "des", captain_count: 0, group_no: 0 },
  { id: 20, name: "송재혁", chapter: "frt", captain_count: 0, group_no: 0 },
  { id: 21, name: "오윤경", chapter: "be", captain_count: 0, group_no: 0 },
  { id: 22, name: "이인표", chapter: "be", captain_count: 0, group_no: 0 },
  { id: 23, name: "김문정", chapter: "svc", captain_count: 0, group_no: 0 },
  { id: 24, name: "이경아", chapter: "frt", captain_count: 0, group_no: 0 },
  { id: 25, name: "신연수", chapter: "svc", captain_count: 0, group_no: 0 },
  { id: 27, name: "전상아", chapter: "stf", captain_count: 0, group_no: 0 },
  { id: 28, name: "이승균", chapter: "frt", captain_count: 0, group_no: 0 },
  { id: 29, name: "나종협", chapter: "be", captain_count: 0, group_no: 0 },
  { id: 30, name: "이혜주", chapter: "des", captain_count: 0, group_no: 0 },
  { id: 31, name: "배상현", chapter: "des", captain_count: 0, group_no: 0 },
  { id: 32, name: "박다솜", chapter: "data", captain_count: 0, group_no: 0 },
  { id: 33, name: "김재은", chapter: "des", captain_count: 0, group_no: 0 },
  { id: 34, name: "김의태", chapter: "data", captain_count: 0, group_no: 0 },
  { id: 35, name: "노혜미", chapter: "data", captain_count: 0, group_no: 0 },
  { id: 36, name: "이승준", chapter: "ops", captain_count: 0, group_no: 0 },
  { id: 37, name: "이형구", chapter: "ops", captain_count: 0, group_no: 0 },
  { id: 38, name: "오영주", chapter: "data", captain_count: 0, group_no: 0 },
  { id: 40, name: "김윤정", chapter: "data", captain_count: 0, group_no: 0 },
  { id: 41, name: "이종형", chapter: "frt", captain_count: 0, group_no: 0 },
  { id: 42, name: "김남상", chapter: "ops", captain_count: 0, group_no: 0 },
  { id: 43, name: "이유진", chapter: "ops", captain_count: 0, group_no: 0 },
  { id: 44, name: "정세화", chapter: "ops", captain_count: 0, group_no: 0 },
  { id: 45, name: "정승호", chapter: "data", captain_count: 0, group_no: 0 },
  { id: 46, name: "강준혁", chapter: "be", captain_count: 0, group_no: 0 },
  { id: 47, name: "조아라", chapter: "stf", captain_count: 0, group_no: 0 },
  { id: 48, name: "고명진", chapter: "be", captain_count: 0, group_no: 0 },
  { id: 49, name: "나규민", chapter: "ops", captain_count: 0, group_no: 0 },
  { id: 50, name: "안현숙", chapter: "ops", captain_count: 0, group_no: 0 },
  { id: 51, name: "노은빈", chapter: "des", captain_count: 0, group_no: 0 },
  { id: 52, name: "박결", chapter: "des", captain_count: 0, group_no: 0 },
  { id: 54, name: "최윤철", chapter: "be", captain_count: 0, group_no: 0 },
  { id: 55, name: "백아리", chapter: "mkt", captain_count: 0, group_no: 0 },
  { id: 56, name: "강웅석", chapter: "data", captain_count: 0, group_no: 0 },
  { id: 57, name: "김영진", chapter: "svc", captain_count: 0, group_no: 0 },
  { id: 58, name: "뉴페이스", chapter: "svc", captain_count: 0, group_no: 0 },
];
