import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "@/assets/globals.css";
import { IBaseNextComponent } from "@/assets/interface";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: IBaseNextComponent) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>app body</div>
        {children}
      </body>
    </html>
  );
}
